name: GitHub-Readme-Activity-Graph

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-activity-graph-svg
    steps:
      - uses: actions/checkout@v4
      - uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: bg_color=0D1117&color=00F0FF&line=00F0FF&point=00F0FF&title_color=00F0FF&hide_border=true&custom_title=Shivang%27s%20Contribution%20Chart&days=30
          output_path: activity-graph/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git diff --staged --quiet || (git commit -m "generated activity-graph-svg [skip ci]" && git pull --rebase origin main && git push)
